version: '3.5'


services:
  filebeat:
    user: root
    image: docker.elastic.co/beats/filebeat:7.16.2
    restart: unless-stopped
    command: filebeat -e -strict.perms=false
    network_mode: host
    volumes:
      - /var/lib/docker/containers:/hostfs/var/lib/docker/containers
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - fbdata:/usr/share/filebeat/data/
volumes:
  fbdata:
    driver: local
