filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /hostfs/var/lib/docker/containers/*/*-json.log
    tags: [“docker-logs”]
    json.keys_under_root: true
    json.add_error_key: true
output.logstash:
  hosts: ["127.0.0.1:5044"]
