version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn mydjangoproject.wsgi:application --bind 0.0.0.0:8000 --access-logfile -
    volumes:
      - ./app/:/home/app/web/
      - ./staticfiles:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
      - ./db_data:/home/app/web/db_data
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./mediafiles:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

