version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn eterex.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/home/app/web/
      - ./app/staticfiles:/home/app/web/staticfiles
      - ./app/mediafiles:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
